services:
  jellyseerr:
    image: fallenbagel/jellyseerr:2.7.3
    container_name: jellyseerr
    environment:
    - LOG_LEVEL=debug
    - TZ=Europe/Moscow
    - PORT=5055 #optional
    ports:
    - 5055:5055
    volumes:
    - jellyseerr-config:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped
    dns: 
    - 9.9.9.9
    networks:
      - proxy
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.jellyseerr.entrypoints=websecure"
    - "traefik.http.routers.jellyseerr.rule=Host(`jellyseerr.home.m1xxos.tech`) || Host(`jellyseerr.m1xxos.tech`)"
    - "traefik.http.services.jellyseerr.loadbalancer.server.port=5055"
    - "traefik.http.routers.jellyseerr.tls=true"

  radarr:
    image: lscr.io/linuxserver/radarr:5.27.5
    container_name: radarr
    environment:
    - PUID=568
    - PGID=568
    - TZ=Europe/Moscow
    expose:
    - 7878
    volumes:
    - radarr-config:/config
    - movies:/movies #optional
    - downloads:/downloads #optional
    restart: always
    networks:
      - proxy
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.radarr.entrypoints=websecure"
    - "traefik.http.routers.radarr.rule=Host(`radarr.home.m1xxos.tech`)"
    - "traefik.http.routers.radarr.service=radarr"
    - "traefik.http.services.radarr.loadbalancer.server.port=7878"
    - "traefik.http.routers.radarr.tls=true"

  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.15
    container_name: sonarr
    environment:
    - PUID=568
    - PGID=568
    - TZ=Europe/Moscow
    expose:
    - 8989
    volumes:
    - sonarr-config:/config
    - tvseries:/tv #optional
    - downloads:/downloads #optional
    restart: always
    networks:
      - proxy
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.sonarr.entrypoints=websecure"
    - "traefik.http.routers.sonarr.service=sonarr"
    - "traefik.http.routers.sonarr.rule=Host(`sonarr.home.m1xxos.tech`)"
    - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
    - "traefik.http.routers.sonarr.tls=true"

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:2.0.5
    container_name: prowlarr
    environment:
    - PUID=568
    - PGID=568
    - TZ=Europe/Moscow
    expose:
    - 9696
    volumes:
    - prowlarr-config:/config
    restart: unless-stopped
    networks:
      - proxy
      - arr
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.prowlarr.entrypoints=websecure"
    - "traefik.http.routers.prowlarr.service=prowlarr"
    - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.home.m1xxos.tech`)"
    - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
    - "traefik.http.routers.prowlarr.tls=true"
    - "traefik.docker.network=traefik_proxy"
  
  cleanuparr:
    image: ghcr.io/cleanuparr/cleanuparr:2.2.3
    container_name: cleanuparr
    restart: unless-stopped
    expose:
      - 11011
    volumes:
      - cleanuparr-config:/config
    environment:
      - PORT=11011
      - BASE_PATH=
      - PUID=568
      - PGID=568
      - UMASK=022
      - TZ=Europe/Moscow
    networks:
      - proxy
      - arr
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11011/health"]
      interval: 30s        # Check every 30 seconds
      timeout: 10s         # Allow up to 10 seconds for response
      start_period: 30s    # Wait 30 seconds before first check
      retries: 3           # Mark unhealthy after 3 consecutive failures
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.cleanuparr.entrypoints=websecure"
    - "traefik.http.routers.cleanuparr.service=cleanuparr"
    - "traefik.http.routers.cleanuparr.rule=Host(`cleanuparr.home.m1xxos.tech`)"
    - "traefik.http.services.cleanuparr.loadbalancer.server.port=11011"
    - "traefik.http.routers.cleanuparr.tls=true"
    - "traefik.docker.network=traefik_proxy"

volumes:
  jellyseerr-config:
  radarr-config:
  sonarr-config:
  prowlarr-config:
  cleanuparr-config:
  tvseries:
    external:
      name: tvseries
  movies:
    external:
      name: movies
  downloads:
    external:
      name: downloads
 
networks:
  proxy:
    external:
      name: traefik_proxy
  arr:
