http:
  routers:
    portainer:
      rule: "Host(`portainer.home.m1xxos.tech`)"
      service: "portainer"
      entryPoints:
      - "websecure"
      - "web"

  services:
    portainer:
      loadBalancer:
        servers:
        - url: "https://192.168.1.128:9443"
        serversTransport: my-insecure-transport

  serversTransports:
    my-insecure-transport:
      insecureSkipVerify: true
