http:
  routers:
    proxmox:
      rule: "Host(`proxmox.home.m1xxos.tech`)"
      service: "proxmox"
      entryPoints:
      - "websecure"
      - "web"

  services:
    proxmox:
      loadBalancer:
      serversTransport: "my-insecure-transport"
      servers:
      - url: "https://192.168.1.134:8006"
