services:
  downloader:
    image: ghcr.io/m1xxos/music-parser:sha-6013d69
    container_name: music-parser
    restart: unless-stopped
    expose:
      - 8080
    networks:
      - proxy
    environment:
      OUTPUT_ROOT: /data/music
      TMP_ROOT: /data/tmp
      DEFAULT_AUDIO_FORMAT: mp3
      DEFAULT_AUDIO_QUALITY: "320"
      HTTP_TIMEOUT_SECONDS: "20"
    user: "568:568" 
    tmpfs:
      - /data/tmp:mode=766,uid=568,gid=568
    volumes:
      - music:/data/music
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mparser.entrypoints=websecure"
      - "traefik.http.services.mparser.loadbalancer.server.port=8080"
      - "traefik.http.routers.mparser.rule=Host(`mparser.home.m1xxos.online`)"
  slskd:
    image: slskd/slskd:0.25.1
    container_name: slskd
    user: "568:568"
    ports:
      - "50300:50300"
    expose:
      - 5030
    networks:
      - proxy
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
      - SLSKD_SHARED_DIR=/music
      - SLSKD_DOWNLOADS_DIR=/music/slskd
    volumes:
      - slskd-data:/app
      - music:/music
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.slskd.entrypoints=websecure"
      - "traefik.http.services.slskd.loadbalancer.server.port=5030"
      - "traefik.http.routers.slskd.rule=Host(`slskd.home.m1xxos.online`)"
  explo:
    image: ghcr.io/lumepart/explo:v1.0.1
    restart: unless-stopped
    container_name: explo
    expose:
      - "7288"
    networks:
      - proxy
    volumes:
      - explo-env:/opt/explo/.env
      - explo-config:/opt/explo/config # required — stores playlist cache and cover art
      - music-explo:/data/ # has to be in the same path you have your music system pointed to (it's recommended to put explo under a subfolder)
      - music-slskd:/slskd/ # if using slskd
    environment:
      - TZ=UTC # Change this to the timezone set in ListenBrainz (default is UTC)
      - WEB_UI=true
      # Web UI credentials (required for login)
      - UI_USERNAME=m1xxos
      - UI_PASSWORD=${EXPLO_PASS}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.explo.entrypoints=websecure"
      - "traefik.http.services.explo.loadbalancer.server.port=7288"
      - "traefik.http.routers.explo.rule=Host(`explo.home.m1xxos.online`)"

networks:
  proxy:
    external:
      name: traefik_proxy

volumes:
  slskd-data:
  explo-config:
  explo-env:
  music:
    external:
      name: music
  music-slskd:
    external:
      name: music-slskd
  music-explo:
    external:
      name: music-explo
